In [7]:
import pandas as pd
print(pd.__version__)
import numpy as np
df=pd.read_csv("Property.csv",sep=';')

3.0.5

LAOD AND EXPLORATION OF DATA

In [6]:
df=pd.read_csv("Property.csv",sep=';')

In [15]:
print(df.head())

   property_id  location_id  \
0       347795            8
1       482892           48
2       555962           75
3       562843         3821
4       686990         3522

                                            page_url property_type      price  \
0  https://www.zameen.com/Property/lahore_model_t...         House  220000000
1  https://www.zameen.com/Property/lahore_multan_...         House   40000000
2  https://www.zameen.com/Property/eden_eden_aven...         House    9500000
3  https://www.zameen.com/Property/gulberg_2_gulb...         House  125000000
4  https://www.zameen.com/Property/allama_iqbal_t...         House   21000000

            location    city province_name   latitude  longitude  baths  \
0         Model Town  Lahore        Punjab  31.483869  74.325686      0
1        Multan Road  Lahore        Punjab  31.431593  74.179980      5
2               Eden  Lahore        Punjab  31.499348  74.416959      0
3            Gulberg  Lahore        Punjab  31.522069  74.355512      7
4  Allama Iqbal Town  Lahore        Punjab  31.506483  74.286017      5

       area   purpose  bedrooms  date_added                  agency  \
0   6 Kanal  For Sale         0  07-17-2019  Real Biz International
1   1 Kanal  For Sale         5  10-06-2018             Khan Estate
2   9 Marla  For Sale         3  07-03-2019         Shahum Estate 2
3   1 Kanal  For Sale         8  04-04-2019                     NaN
4  11 Marla  For Sale         6  04-04-2019                     NaN

                     agent
0               Usama Khan
1         mohsinkhan and B
2  Babar Hameed, Raja Omar
3                      NaN
4                      NaN

In [17]:
print(df.shape)

(191393, 17)

In [18]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 191393 entries, 0 to 191392
Data columns (total 17 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   property_id    191393 non-null  int64
 1   location_id    191393 non-null  int64
 2   page_url       191393 non-null  str
 3   property_type  191393 non-null  str
 4   price          191393 non-null  int64
 5   location       191393 non-null  str
 6   city           191393 non-null  str
 7   province_name  191393 non-null  str
 8   latitude       191393 non-null  float64
 9   longitude      191393 non-null  float64
 10  baths          191393 non-null  int64
 11  area           191393 non-null  str
 12  purpose        191393 non-null  str
 13  bedrooms       191393 non-null  int64
 14  date_added     191393 non-null  str
 15  agency         144014 non-null  str
 16  agent          144013 non-null  str
dtypes: float64(2), int64(5), str(10)
memory usage: 24.8 MB

In [19]:
df.describe()

,property_id,location_id,price,latitude,longitude,baths,bedrooms
count,1.913930e+05,191393.000000,1.913930e+05,191393.000000,191393.000000,191393.000000,191393.000000
mean,1.573170e+07,4224.580350,1.644655e+07,30.104593,71.572992,2.865956,3.171516
std,2.215249e+06,3719.125201,3.416412e+07,3.645941,3.080463,2.435332,1.952403
min,8.657500e+04,1.000000,0.000000e+00,11.052446,25.906027,0.000000,0.000000
25%,1.511867e+07,1057.000000,8.000000e+04,24.972287,67.152597,0.000000,2.000000
50%,1.676385e+07,3233.000000,7.300000e+06,31.463563,73.077743,3.000000,3.000000
75%,1.715282e+07,7182.000000,1.800000e+07,33.550869,74.228218,4.000000,4.000000
max,1.769386e+07,14246.000000,2.000000e+09,73.184088,80.161430,403.000000,68.000000

In [22]:
df.isnull().sum()

property_id          0
location_id          0
page_url             0
property_type        0
price                0
location             0
city                 0
province_name        0
latitude             0
longitude            0
baths                0
area                 0
purpose              0
bedrooms             0
date_added           0
agency           47379
agent            47380
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [24]:
df.columns

Index(['property_id', 'location_id', 'page_url', 'property_type', 'price',
       'location', 'city', 'province_name', 'latitude', 'longitude', 'baths',
       'area', 'purpose', 'bedrooms', 'date_added', 'agency', 'agent'],
      dtype='str')

**Total Records**=191,393
**Total Features**=17
**Missing values**:
  agency=47,379 missing values
  agent=47,380 missing values
**Note:** 
  Missing values in 'agency' and 'agent' represent listings post by owners rather than commercial agents.

DATA CLEANING

In [ ]:
'''Fill missing values'''
df['agency']=df['agency'].fillna('owner')
df['agent']=df['agent'].fillna('owner')

In [13]:
print(df['agency'].isnull().sum())
print(df['agent'].isnull().sum())

0
0

In [16]:
df.head(5)

,property_id,location_id,page_url,property_type,price,location,city,province_name,latitude,longitude,baths,area,purpose,bedrooms,date_added,agency,agent
0,347795,8,https://www.zameen.com/Property/lahore_model_t...,House,220000000,Model Town,Lahore,Punjab,31.483869,74.325686,0,6 Kanal,For Sale,0,07-17-2019,Real Biz International,Usama Khan
1,482892,48,https://www.zameen.com/Property/lahore_multan_...,House,40000000,Multan Road,Lahore,Punjab,31.431593,74.179980,5,1 Kanal,For Sale,5,10-06-2018,Khan Estate,mohsinkhan and B
2,555962,75,https://www.zameen.com/Property/eden_eden_aven...,House,9500000,Eden,Lahore,Punjab,31.499348,74.416959,0,9 Marla,For Sale,3,07-03-2019,Shahum Estate 2,"Babar Hameed, Raja Omar"
3,562843,3821,https://www.zameen.com/Property/gulberg_2_gulb...,House,125000000,Gulberg,Lahore,Punjab,31.522069,74.355512,7,1 Kanal,For Sale,8,04-04-2019,owner,owner
4,686990,3522,https://www.zameen.com/Property/allama_iqbal_t...,House,21000000,Allama Iqbal Town,Lahore,Punjab,31.506483,74.286017,5,11 Marla,For Sale,6,04-04-2019,owner,owner

In [18]:
'''Conversion to one unit of column 'Area' '''
df['area_raw_num']= df['area'].str.extract(r'(\d+)').astype(float)

In [20]:
df[['area','area_raw_num']].head(5)

       area  area_raw_num
0   6 Kanal           6.0
1   1 Kanal           1.0
2   9 Marla           9.0
3   1 Kanal           1.0
4  11 Marla          11.0

In [21]:
df['area_sqft']=np.nan

In [22]:
df[['area_sqft']].head(5)

   area_sqft
0        NaN
1        NaN
2        NaN
3        NaN
4        NaN

In [23]:
#convert Kanal rows
df.loc[df['area'].str.contains('kanal',case=False),'area_sqft'] = df['area_raw_num']* 5445 
#convert Marla rows
df.loc[df['area'].str.contains('marla',case=False),'area_sqft'] = df['area_raw_num']*225

In [24]:
df[['area','area_sqft','area_raw_num']].head(5)

       area  area_sqft  area_raw_num
0   6 Kanal    32670.0           6.0
1   1 Kanal     5445.0           1.0
2   9 Marla     2025.0           9.0
3   1 Kanal     5445.0           1.0
4  11 Marla     2475.0          11.0

In [27]:
df.columns

Index(['property_id', 'location_id', 'page_url', 'property_type', 'price',
       'location', 'city', 'province_name', 'latitude', 'longitude', 'baths',
       'area', 'purpose', 'bedrooms', 'date_added', 'agency', 'agent',
       'area_raw_num', 'area_sqft'],
      dtype='str')

In [28]:
df.head(5)

,property_id,location_id,page_url,property_type,price,location,city,province_name,latitude,longitude,baths,area,purpose,bedrooms,date_added,agency,agent,area_raw_num,area_sqft
0,347795,8,https://www.zameen.com/Property/lahore_model_t...,House,220000000,Model Town,Lahore,Punjab,31.483869,74.325686,0,6 Kanal,For Sale,0,07-17-2019,Real Biz International,Usama Khan,6.0,32670.0
1,482892,48,https://www.zameen.com/Property/lahore_multan_...,House,40000000,Multan Road,Lahore,Punjab,31.431593,74.179980,5,1 Kanal,For Sale,5,10-06-2018,Khan Estate,mohsinkhan and B,1.0,5445.0
2,555962,75,https://www.zameen.com/Property/eden_eden_aven...,House,9500000,Eden,Lahore,Punjab,31.499348,74.416959,0,9 Marla,For Sale,3,07-03-2019,Shahum Estate 2,"Babar Hameed, Raja Omar",9.0,2025.0
3,562843,3821,https://www.zameen.com/Property/gulberg_2_gulb...,House,125000000,Gulberg,Lahore,Punjab,31.522069,74.355512,7,1 Kanal,For Sale,8,04-04-2019,owner,owner,1.0,5445.0
4,686990,3522,https://www.zameen.com/Property/allama_iqbal_t...,House,21000000,Allama Iqbal Town,Lahore,Punjab,31.506483,74.286017,5,11 Marla,For Sale,6,04-04-2019,owner,owner,11.0,2475.0

In [29]:
'''Garbage values = 0 '''
# Check zeroes across all numeric columns in one shot
zero_summary = (df.select_dtypes(include='number') == 0).sum()
print("Zero counts per numeric column:\n", zero_summary[zero_summary > 0])

Zero counts per numeric column:
 price               3
baths           48130
bedrooms        24959
area_raw_num      265
area_sqft         265
dtype: int64